name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python:
        - 3.7
        - 3.8
        - 3.9
        - 3.10
        - 3.11
        django-version:
        - "2.2,<3.0"
        - "3.2,<4.0"
        - "4.0,<4.1"
        - "4.1,<4.2"

    steps:
    - name: Installing wkhtmltopdf dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y libxrender1 libfontconfig1 zlib1g libfreetype6 libx11-6 libxext6
    - name: Installing wkhtmltopdf
      run: |
        wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
        tar xf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
        mkdir -p ~/bin
        cp ./wkhtmltox/bin/wkhtmltopdf ~/bin
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v2
    - name: Install Dependencies on ${{ matrix.python-version }}
      run: |
        python -m pip install --upgrade pip
        pip install "Django>=${{ matrix.django-version }}"
        pip install -r test_requirements.txt
        pip install .
    - name: Run Tests
      run: |
        WKHTMLTOPDF_CMD=~/bin/wkhtmltopdf make test
